### ISSUE TITLE
Apple Instruments reports 4731 memory leaks on launch

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zec-qt-wallet#30] opened 2018-11-06 12:52 UTC
Reproducibility: always

Steps:
Run a leaks check on zec-qt-wallet using Apple Instruments (part of Xcode developer tools).

What happened:
![screen shot 2018-11-06 at 14 48 23](https://user-images.githubusercontent.com/227442/48065405-3cd8f280-e1d3-11e8-824f-76190a8bd303.png)

Expected result:
No leaks.

**Comment by adityapk00** [comment] 2018-11-06 16:00
Thanks for running it through the leak detector! Unfortunately, I don't have access to a Mac, so I can't reproduce this :(

I run it through valgrind on Linux, which doesn't seem to report these leaks. 

Is there any way you can attach the report/output of XCode so I can take a deeper look?

**Comment by rex4539** [comment] 2018-11-07 11:28
If I'm reading those correctly, it appears most leaks occur after calling `RPC::refreshZECPrice()`

**Comment by adityapk00** [comment] 2018-11-07 19:17
Thank you. This helps a lot!

**Comment by adityapk00** [comment] 2018-11-14 17:35
I added a bunch of fixes in v0.3.1

However, it seems like Qt shows a lot of memory leaks if run via Instruments if the app exits when some RPC calls are pending. Qt framework is deciding that the app is exiting anyway, no need to clean up (probably as an optimization). But when run through Instruments these show up as leaks. 

I look into what other projects are doing here, but closing this for now.

**Closed by adityapk00** 2018-11-14 17:35 UTC
